baseURL = "https://jlansley.github.io/"
languageCode = "en-us"
title = "Joseph Lansley"

[params]
  name = "Joseph Lansley"
  field = "Economics"
  institution = "University of Rochester"
  tagline = "PhD Candidate in Economics, University of Rochester"
  email = "jlansley@ur.rochester.edu"
  cv_file = "/files/cv.pdf"
  github = "https://github.com/jlansley"
  linkedin = "https://linkedin.com"

[markup.goldmark.renderer]
  unsafe = true
